name: utmlostnfound
description: "A new Flutter project."
publish_to: 'none'
version: 0.4.3

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.2
  marquee: ^2.3.0
  google_fonts: ^6.2.1
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  cloudinary_api: ^1.0.2
  cloudinary_url_gen: ^1.6.0
  cloudinary_flutter: ^1.3.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  uuid: ^4.5.1
  http: ^1.2.2
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  firebase_messaging: ^15.1.6
  awesome_notifications: ^0.10.0
  fl_chart: ^0.69.2
  month_picker_dialog: ^5.1.3
  syncfusion_flutter_charts: ^28.1.36
  pdf: ^3.11.1
  csv: ^6.0.0
  open_file: ^3.5.10
  printing: ^5.13.4
  flutter_pdfview: ^1.3.4
  path_provider: ^2.1.5
  syncfusion_flutter_pdfviewer: ^28.1.36
  mime: ^2.0.0
  http_parser: ^4.0.2
  dropdown_search: ^6.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  icons_launcher: ^3.0.0

icons_launcher:
  image_path: "assets/icons/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/asset1.jpg
    - assets/asset2.jpg
    - assets/asset3.jpg
    - assets/home.png
    - assets/icons/icon.png
    - assets/default_profile.png